### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by soulwu** [hax/babel-plugin-transform-es2015-generator-return#24]
If use this plugin together whith `babel-plugin-transform-es2015-block-scoping`, there is a `RangeError` occurred.

```
RangeError: src/middlewares/mapi.js: Maximum call stack size exceeded
    at Scope.hasBinding (/Users/soulwu/Documents/work/git/actapi/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:1201:51)
    at Scope.parentHasBinding (/Users/soulwu/Documents/work/git/actapi/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:1212:39)
    at Scope.hasBinding (/Users/soulwu/Documents/work/git/actapi/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:1204:14)
    at Scope.parentHasBinding (/Users/soulwu/Documents/work/git/actapi/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:1212:39)
    at Scope.hasBinding (/Users/soulwu/Documents/work/git/actapi/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:1204:14)
    at Scope.parentHasBinding (/Users/soulwu/Documents/work/git/actapi/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:1212:39)
    at Scope.hasBinding (/Users/soulwu/Documents/work/git/actapi/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:1204:14)
    at Scope.parentHasBinding (/Users/soulwu/Documents/work/git/actapi/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:1212:39)
    at Scope.hasBinding (/Users/soulwu/Documents/work/git/actapi/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:1204:14)
    at Scope.parentHasBinding (/Users/soulwu/Documents/work/git/actapi/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:1212:39)
    at Scope.hasBinding (/Users/soulwu/Documents/work/git/actapi/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:1204:14)
```

my env:

node: 4.2.1
npm: 2.14.7
babel-plugin-transform-es2015-block-scoping: 6.9.0
babel-plugin-transform-es2015-generator-return: 1.1.0

**Comment by hax** [comment]
Could you provide a minimal source code sample which can trigger such error?

**Comment by soulwu** [comment]
@hax 

``` js
function *mapi(next) {
  const ctx = this;
  this.mapi = {
    invoke: co.wrap(function *invode(moduleName, params = {}) {
      const module = modules[moduleName];
      if (!module) {
        ctx.throw('error', {retCode: 100004});
      }
    })
  };
  yield *next;
}
```

![image](https://cloud.githubusercontent.com/assets/1633638/16033498/d58a449e-323e-11e6-8246-18eb741d41c9.png)

**Comment by hax** [comment]
@soulwu Fixed. Thank you for report.
